version: 2
jobs:
  build:
    docker:
    - image: haskell:latest
    steps:
    - checkout
    - run: cabal sandbox init
    - run: cabal update
    # - run: cabal install -j
    - run: cabal install --enable-tests --enable-documentation
    - run: cabal build

  test:
    docker:
    - image: haskell:latest
    steps:
    - checkout
    - run: cabal sandbox init
    - run: cabal update
    - run: cabal install --enable-tests --enable-documentation
    - run: cabal test

workflows:
  version: 2
  build_and_test:
    jobs:
    - test
    - build
